### ISSUE TITLE
New Puppet: PuppetQQ

### ISSUE THREAD

**Issue by huan** [wechaty/wishlist#9]
It seems that we will be very easy to support QQ in Wechaty.

### See Also

* [SmartQQ robot written in JavaScript, using ES7 async/await features](https://github.com/rocket1184/qq-bot-rebown)
* [SmartQQ（WebQQ）的Api ，你可以用它实现自己的QQ 机器人 a qq robot based on smartqq (webqq) api](https://github.com/ScienJus/smartqq)
* [对SmartQQ API的C#封装。（由于作者懒出了一定境界现已停止维护）](https://github.com/TJYSunset/DumbQQ)
* [SmartQQ（WebQQ）的Api ，你可以用它实现自己的QQ 机器人 a qq robot based on smartqq (webqq) api](https://github.com/ScienJus/smartqq/tree/java8)
* [使用Perl语言（不会没关系）编写的smartqq/webqq客户端框架（非GUI），可通过插件提供基于HTTP协议的api接口供其他语言或系统调用](https://github.com/sjdy521/Mojo-Webqq)
* [经典QQ表情/文字替换](https://github.com/fritx/qqface)

**Comment by jihuayu** [comment]
- [mirai 全开源 高效率 QQ机器人/Android QQ协议支持库 for JVM / Android](https://github.com/mamoe/mirai)

**Comment by huan** [comment]
将 Kotlin 的代码库，封装为 Node.js 可以加载的例子： [Demo of using Kotlin with Node.js](https://github.com/wojta/kotlin-nodejs-experiment/)

**Comment by huan** [comment]
Merge to https://github.com/wechaty/summer/issues/81
